---
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: alvarofpp/app-jinja2-dev
    container_name: app_jinja2_dev
    command: streamlit run app/app.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
